# Pre-commit hooks for KRR MCP Server
# Run: pre-commit install to set up the hooks
# Run: pre-commit run --all-files to run on all files

repos:
  # Built-in hooks for basic file maintenance
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: debug-statements
        exclude: \.md$

  # Python code formatting with black (matches GitHub Actions)
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: ["--line-length=88"]
        exclude: \.md$

  # Import sorting with isort (matches GitHub Actions)
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile=black", "--line-length=88"]
        exclude: \.md$

  # Linting with flake8 (matches GitHub Actions - critical errors only)
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args:
          - "--max-line-length=88"
          - "--max-complexity=10"
          - "--select=E9,F63,F7,F82"
          - "--extend-ignore=E203,W503"
        exclude: \.md$

  # Security scanning with bandit (matches GitHub Actions)
  - repo: https://github.com/pycqa/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ["-r", "src", "--skip", "B112"]
        pass_filenames: false
        files: ^src/

  # Type checking with mypy (matches GitHub Actions)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.0
    hooks:
      - id: mypy
        args: ["src"]
        pass_filenames: false
        additional_dependencies:
          - "types-pyyaml>=6.0.12.20250516"
          - "structlog>=23.0.0"
          - "pydantic>=2.0.0"
          - "typer>=0.9.0"
          - "python-dotenv>=1.0.0"
          - "fastmcp>=0.1.0"
          - "httpx>=0.25.0"

# Configure specific settings
default_language_version:
  python: python3

# Exclude patterns
exclude: |
  (?x)^(
    htmlcov/.*|
    test-reports/.*|
    \.venv/.*|
    \.git/.*|
    __pycache__/.*|
    \.coverage.*
  )$
